import { GameConfig } from './types';

export const GAME_CONFIGS: Record<string, GameConfig> = {
  'crazy-colors': {
    gameId: 'crazy-colors',
    title: 'Crazy Color',
    titleAmharic: 'ክሬዚ ከለርስ',
    genre: 'Precision Reflex',
    tagline: 'Tap to bounce the ball upward through matching color obstacles!',
    description: 'Electrifying reflex challenge. Guide your colored sphere through rotating multi-colored geometric shapes. You can only pass through segments that match your ball.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-fuchsia-500 via-purple-600 to-indigo-700',
      accentColor: '#D946EF',
      badgeBg: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/40',
      cardBg: 'bg-slate-900/90 border-fuchsia-500/30',
      iconEmoji: '🎨',
      bannerBg: 'bg-gradient-to-b from-purple-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Tap rhythmically to keep the bouncing ball airborne and time your ascent through matching color segments.',
      rules: [
        'Tap anywhere on the screen to make the ball hop upward.',
        'The ball can only pass through barriers that match its current color.',
        'Touching any mismatched color segment causes the ball to burst.',
        'Collect Color Switcher orbs to morph into a new random color.',
        'Collect yellow stars to earn score points.',
      ],
      controls: 'Tap the screen to bounce upward.',
      proTips: [
        'Patience is key: bounce gently in place until the matching color segment rotates into position.',
        'Do not rush into a shape immediately after picking up a color switch.',
      ],
    },
    achievements: [
      { id: 'cc_star_collector', title: 'Star Hunter', desc: 'Collect 25 stars', icon: '⭐', maxProgress: 25 },
      { id: 'cc_prism', title: 'Prism Master', desc: 'Pass through 10 color rings', icon: '🌈', maxProgress: 10 },
      { id: 'cc_perfectionist', title: 'Color Guru', desc: 'Reach Level 15', icon: '🎖️', maxProgress: 15 },
    ],
    about: {
      version: '2.0.1',
      developer: 'TelePlay Game Studios',
      engine: 'Chromatic 2D Physics Engine',
      features: ['Neon glow visual effects', '40 hand-tuned level orbits', 'Precise touch controls'],
    },
  },

  'juicy-match': {
    gameId: 'juicy-match',
    title: 'Candy Juicy',
    titleAmharic: 'ኬንዲ ጁሲ',
    genre: 'Fruit Match-3',
    tagline: 'Slice and match tropical fruits in vivid splash puzzles!',
    description: 'Embark on a refreshing tropical orchard journey swapping watermelons, kiwis, oranges, and strawberries with juicy splatters.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-emerald-500 via-teal-500 to-cyan-600',
      accentColor: '#10B981',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '🍉',
      bannerBg: 'bg-gradient-to-b from-emerald-950/60 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Swap fruits to match 3 or more of the same variety and pop obstacles like jelly and fruit baskets.',
      rules: [
        'Match 3 fruits in any orthogonal line to harvest them.',
        'Match 4 fruits to create a Splash Juice Rocket.',
        'Match 5 in a row for the Rainbow Blender that clears all fruits of a type.',
        'Clear all jelly layers and complete level quotas before moves run out.',
      ],
      controls: 'Tap or drag a fruit toward an adjacent fruit to swap.',
      proTips: [
        'Focus on clearing corner jellies early as they are harder to reach.',
        'Save your boosters for tricky levels with frozen fruit cages.',
      ],
    },
    achievements: [
      { id: 'jm_harvest', title: 'Fruit Harvester', desc: 'Match 100 tropical fruits', icon: '🍓', maxProgress: 100 },
      { id: 'jm_splash', title: 'Mega Splash', desc: 'Create 10 Juice Rockets', icon: '🚀', maxProgress: 10 },
      { id: 'jm_orchard', title: 'Orchard Champ', desc: 'Clear 15 juicy stages', icon: '🏆', maxProgress: 15 },
    ],
    about: {
      version: '3.1.0',
      developer: 'TelePlay Game Studios',
      engine: 'JuiceFX WebGL Match Engine',
      features: ['Realistic splash particles', 'Tactile haptic pops', 'Orchard campaign map'],
    },
  },

  'pop-piano': {
    gameId: 'pop-piano',
    title: 'Pop Piano',
    titleAmharic: 'ፖፕ ፒያኖ',
    genre: 'Rhythm Music Game',
    tagline: 'Tap falling black piano keys to play beloved melodies with rhythm precision!',
    description: 'Clean ivory 4-lane rhythm tiles game. Tap falling black rectangular keys in synchronization with musical tempo. Don\'t miss any tiles or tap the white canvas.',
    hasLevels: true,
    totalLevels: 30,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-purple-600 via-indigo-600 to-slate-900',
      accentColor: '#6366F1',
      badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
      cardBg: 'bg-slate-900/90 border-indigo-500/30',
      iconEmoji: '🎹',
      bannerBg: 'bg-gradient-to-b from-indigo-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Tap the descending black piano tiles as they cross the strike line at the bottom of the screen.',
      rules: [
        'Tap the black tiles to trigger authentic harmonic piano notes.',
        'Tapping near the bottom target line yields "PERFECT" score ratings.',
        'Tapping the ivory white background results in immediate failure.',
        'Letting any black tile drop past the bottom causes a miss.',
        'Complete the full song score to clear the level.',
      ],
      controls: 'Tap the 4 lanes directly on falling black tiles.',
      proTips: [
        'Rest your index and middle fingers on each side of the screen for two-hand play.',
        'Listen to the music melody rhythm to anticipate rapid note cascades.',
      ],
    },
    achievements: [
      { id: 'pp_perfect_run', title: 'Virtuoso', desc: 'Score 10 consecutive PERFECT taps', icon: '🎵', maxProgress: 10 },
      { id: 'pp_melody_champ', title: 'Maestro', desc: 'Clear 5 songs without miss', icon: '🎼', maxProgress: 5 },
      { id: 'pp_400_score', title: 'Grand Pianist', desc: 'Reach 400 tournament points', icon: '🎹', maxProgress: 400 },
    ],
    about: {
      version: '2.5.0',
      developer: 'TelePlay Game Studios',
      engine: 'Harmonic Polyphonic Audio Engine',
      features: ['Instant zero-latency tap', '400 PTS normalized scoring', '30 classical & modern tracks'],
    },
  },

  'world-legends': {
    gameId: 'world-legends',
    title: 'Word Legend',
    titleAmharic: 'ዎርድ ሌጀንድስ',
    genre: 'Word Puzzle',
    tagline: 'Connect letter tiles to discover hidden words and expand vocabulary!',
    description: 'Swipe across the circular letter dial to build valid Ethiopian and international words, uncover bonus anagrams, and master levels.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'WORDS',
    theme: {
      primaryGradient: 'from-amber-500 via-orange-500 to-yellow-600',
      accentColor: '#F59E0B',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '🔤',
      bannerBg: 'bg-gradient-to-b from-amber-950/60 via-stone-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Form valid words by connecting the given letters in the letter dial to fill the crossword grid.',
      rules: [
        'Swipe through adjacent letters to spell words.',
        'Words must match the crossword crossword slots on the board.',
        'Discover extra dictionary words to fill your Bonus Coin jar.',
        'Shuffle letters when you are stuck to see new anagram patterns.',
        'Use the Hint magnifying glass if you need the first letter revealed.',
      ],
      controls: 'Touch and swipe from letter to letter without lifting your finger.',
      proTips: [
        'Look for common prefixes (UN, RE) and suffixes (ED, ING, S).',
        'Find shorter 3-letter combinations first to open up clues for longer words.',
      ],
    },
    achievements: [
      { id: 'wl_word_smith', title: 'Word Smith', desc: 'Solve 10 crossword levels', icon: '📖', maxProgress: 10 },
      { id: 'wl_lexicon', title: 'Lexicon Master', desc: 'Discover 25 bonus words', icon: '🧠', maxProgress: 25 },
      { id: 'wl_speedy', title: 'Speed Reader', desc: 'Solve a level in under 30 seconds', icon: '⚡', maxProgress: 1 },
    ],
    about: {
      version: '1.8.2',
      developer: 'TelePlay Game Studios',
      engine: 'React Vector Lexical Engine',
      features: ['Bilingual word banks', 'Anagram discovery solver', 'Vocabulary expansion'],
    },
  },

  'candy-blast': {
    gameId: 'candy-blast',
    title: 'Candy Crush',
    titleAmharic: 'ኬንዲ ክራሽ',
    genre: 'Match-3 Puzzle',
    tagline: 'Swap delicious candies to create mouthwatering combos!',
    description: 'Switch and match vibrant confectionery candies in this sugary puzzle adventure to progress through delightful levels.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-pink-500 via-rose-500 to-purple-600',
      accentColor: '#F43F5E',
      badgeBg: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
      cardBg: 'bg-slate-900/90 border-pink-500/30',
      iconEmoji: '🍬',
      bannerBg: 'bg-gradient-to-b from-pink-900/60 via-purple-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Swap adjacent candies to create horizontal or vertical rows of 3 or more identical sweets to clear them from the board.',
      rules: [
        'Match 3 candies of the same color to pop them and score points.',
        'Match 4 candies in a row to create a Striped Candy that clears entire lines.',
        'Match 5 candies in an L or T shape to create a Wrapped Candy with explosive radius.',
        'Match 5 in a straight line to produce a Color Bomb that clears all candies of one color.',
        'Complete the target score before running out of moves.',
      ],
      controls: 'Tap or drag a candy toward an adjacent tile to swap positions.',
      proTips: [
        'Prioritize moves near the bottom of the board to trigger cascade chain reactions.',
        'Combine two special candies (like Color Bomb + Striped Candy) for massive board-clearing effects.',
      ],
    },
    achievements: [
      { id: 'cb_first_match', title: 'Sugar Rush', desc: 'Complete your first candy match', icon: '🍬', maxProgress: 1 },
      { id: 'cb_combo_master', title: 'Sugar Star', desc: 'Trigger a 4x cascade combo', icon: '⭐', maxProgress: 4 },
      { id: 'cb_color_bomb', title: 'Confectionery King', desc: 'Create 5 Color Bombs', icon: '👑', maxProgress: 5 },
    ],
    about: {
      version: '2.4.0',
      developer: 'TelePlay Game Studios',
      engine: 'HTML5 WebGL Canvas Engine',
      features: ['Dynamic physics cascades', 'Special candy fusions', 'Offline play support'],
    },
  },

  'soccer-shooter': {
    gameId: 'soccer-shooter',
    title: 'Soccer Shooter',
    titleAmharic: 'ሶከር ሹተር',
    genre: 'Hex Ball Match-3',
    tagline: 'Kick soccer balls into goal clusters to clear the tournament grid!',
    description: 'Strategic tournament shooting game with soccer theme. Aim balls using trajectory guidelines into hexagonal clusters of country colors to pop goals.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-blue-600 via-cyan-600 to-indigo-800',
      accentColor: '#0284C7',
      badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
      cardBg: 'bg-slate-900/90 border-blue-500/30',
      iconEmoji: '🥅',
      bannerBg: 'bg-gradient-to-b from-blue-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Aim your soccer ball into matching clusters of 3 or more balls in the goal net to pop them.',
      rules: [
        'Aim with the dashed guideline.',
        'Release to shoot your soccer ball toward the goal ceiling.',
        'Connect 3 balls of the same national pattern to score a pop.',
        'Clear all balls before they descend below the danger penalty line.',
      ],
      controls: 'Touch and drag to aim, release to shoot.',
      proTips: [
        'Use the side goalposts to bank shots into tight gaps.',
        'Cut off high anchoring clusters to drop large chunks in one shot.',
      ],
    },
    achievements: [
      { id: 'ss_goal_getter', title: 'Goal Getter', desc: 'Pop 30 soccer ball clusters', icon: '⚽', maxProgress: 30 },
      { id: 'ss_clean_sheet', title: 'Clean Sheet', desc: 'Clear a level without foul warnings', icon: '🧤', maxProgress: 1 },
      { id: 'ss_cup_winner', title: 'World Cup Winner', desc: 'Conquer Level 20', icon: '🏆', maxProgress: 20 },
    ],
    about: {
      version: '2.0.0',
      developer: 'TelePlay Game Studios',
      engine: 'Hexagonal Soccer Physics Engine',
      features: ['National country jerseys', 'Bank-shot laser lines', '40 cup stages'],
    },
  },

  'dama': {
    gameId: 'dama',
    title: 'Dama',
    titleAmharic: 'ባህላዊ የዳማ ጨዋታ',
    genre: 'Traditional Board Game',
    tagline: 'Authentic Ethiopian Dama / Draughts strategy against smart AI!',
    description: 'Master the traditional Ethiopian checkers board game played across Ethiopian coffee houses. Outmaneuver the AI opponent with multi-hop captures and crown your kings.',
    hasLevels: true,
    totalLevels: 30,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-amber-700 via-yellow-800 to-stone-900',
      accentColor: '#B45309',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '👑',
      bannerBg: 'bg-gradient-to-b from-stone-950 via-amber-950/50 to-slate-950',
    },
    howToPlay: {
      summary: 'Move pieces diagonally across dark squares, jumping over opponent pieces to capture them.',
      rules: [
        'Regular pieces move diagonally forward one step.',
        'Captures are mandatory whenever an opposing piece is adjacent with an empty landing cell behind it.',
        'Chain multiple jumps in a single turn to capture multiple pieces.',
        'Reach the opponent\'s back row to promote your piece into a powerful flying King.',
        'A King can fly diagonally across multiple empty squares to strike.',
        'Win by capturing all opponent pieces or blocking all their legal moves.',
      ],
      controls: 'Tap your piece to highlight valid destination squares, then tap target square.',
      proTips: [
        'Control the center of the board to limit the AI\'s mobility.',
        'Protect your back row pieces as long as possible to delay opponent promotions.',
      ],
    },
    achievements: [
      { id: 'dama_first_capture', title: 'First Strike', desc: 'Capture an opponent piece', icon: '♟️', maxProgress: 1 },
      { id: 'dama_crowned', title: 'Crowned King', desc: 'Promote a piece into a King', icon: '👑', maxProgress: 1 },
      { id: 'dama_grandmaster', title: 'Addis Grandmaster', desc: 'Defeat Level 20 AI', icon: '🏆', maxProgress: 20 },
    ],
    about: {
      version: '2.2.0',
      developer: 'TelePlay Game Studios',
      engine: 'Minimax AI Strategy Engine',
      features: ['Authentic Ethiopian Dama rules', 'Handcrafted rustic wood board', '30 progressive AI ranks'],
    },
  },

  'button-soccer': {
    gameId: 'button-soccer',
    title: 'Button Soccer',
    titleAmharic: 'ባተን ሶከር 2026',
    genre: 'Turn-Based Tabletop Soccer',
    tagline: 'Aim your button player tokens and strike goals against national champions!',
    description: 'Authentic 2026 tabletop button soccer championship. Select your national team (Ethiopia, Brazil, Argentina, Germany), aim disc trajectories with power arrows, and score goals.',
    hasLevels: true,
    totalLevels: 20,
    scoreType: 'score',
    scoreLabel: 'WINS',
    theme: {
      primaryGradient: 'from-emerald-700 via-teal-800 to-green-950',
      accentColor: '#10B981',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '🔘',
      bannerBg: 'bg-gradient-to-b from-green-950 via-emerald-950/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Turn-based table soccer: pull back on your team button tokens to aim trajectory and power, and strike the ball into the opponent net.',
      rules: [
        'Players take turns aiming and striking one button token.',
        'Drag backward from your button player to adjust angle and kicking power.',
        'Release to launch your button toward the ball or into opponent territory.',
        'Score target number of goals (e.g. 3 goals) to win the match.',
        'Use wall rebounds to curve around defenders.',
      ],
      controls: 'Touch and pull back on your button token to aim, release to shoot.',
      proTips: [
        'Bank your shots off side cushions to bypass defensive walls.',
        'Position one button as a sweeper right in front of your net.',
      ],
    },
    achievements: [
      { id: 'bs_first_strike', title: 'Table Striker', desc: 'Score your first button goal', icon: '⚽', maxProgress: 1 },
      { id: 'bs_derby_win', title: 'Derby Champion', desc: 'Win match with Ethiopian national team', icon: '🇪🇹', maxProgress: 1 },
      { id: 'bs_trophy_cup', title: 'Cup Winner', desc: 'Win the 2026 Table Championship', icon: '🏆', maxProgress: 1 },
    ],
    about: {
      version: '2.5.0',
      developer: 'TelePlay Game Studios',
      engine: 'Rigid Body Disc Physics 2D/3D',
      features: ['Official national flag discs', 'Realistic table rebounds', 'Championship tournament mode'],
    },
  },

  'soccer-ping-pong': {
    gameId: 'soccer-ping-pong',
    title: 'Soccer Ping Pong',
    titleAmharic: 'ሶከር ፒንግ ፖንግ',
    genre: '3D Soccer Arcade',
    tagline: 'Defend your soccer goal and curve power shots against rival keepers!',
    description: 'Electrifying 3D stadium hybrid soccer game. Control your goalkeeper paddle, deflect balls with spin curves, and beat rival national AI keepers across 20 tournament stadiums.',
    hasLevels: true,
    totalLevels: 20,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-emerald-600 via-green-600 to-teal-800',
      accentColor: '#10B981',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '⚽',
      bannerBg: 'bg-gradient-to-b from-emerald-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Protect your net and deflect the soccer ball past the opposing goalkeeper to score 3 goals before they do.',
      rules: [
        'Move your paddle left and right across your goal line.',
        'Hit the ball with the paddle edges to apply heavy curve and spin.',
        'First player to score the target number of goals wins the match.',
        'Winning unlocks the next stadium tier and national rival team.',
      ],
      controls: 'Slide finger or move mouse horizontally to position your goalie paddle.',
      proTips: [
        'Strike the ball while moving sideways to impart sharp deflection angles.',
        'Watch the opponent keeper\'s movement: wait for them to over-commit to one side.',
      ],
    },
    achievements: [
      { id: 'spp_first_goal', title: 'Clean Strike', desc: 'Score your first goal', icon: '⚽', maxProgress: 1 },
      { id: 'spp_hat_trick', title: 'Hat-Trick', desc: 'Score 3 goals in one match', icon: '🎩', maxProgress: 3 },
      { id: 'spp_stadium_champ', title: 'Stadium Champion', desc: 'Win in the Grand Addis Arena', icon: '🏟️', maxProgress: 1 },
    ],
    about: {
      version: '2.6.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 3D Stadium Field Simulation',
      features: ['20 national league stages', 'Realistic ball spin physics', 'Pyrotechnic goal celebrations'],
    },
  },
};

export const getGameConfig = (gameId: string): GameConfig => {
  return (
    GAME_CONFIGS[gameId] || {
      gameId,
      title: gameId.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      titleAmharic: 'ጨዋታ',
      genre: 'Arcade Game',
      tagline: 'Play and compete for tournament glory!',
      description: 'Engaging tournament game with full leaderboard tracking and skill challenges.',
      hasLevels: true,
      totalLevels: 40,
      scoreType: 'score',
      scoreLabel: 'PTS',
      theme: {
        primaryGradient: 'from-blue-600 via-indigo-600 to-purple-700',
        accentColor: '#3B82F6',
        badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
        cardBg: 'bg-slate-900/90 border-blue-500/30',
        iconEmoji: '🎮',
      },
      howToPlay: {
        summary: 'Follow the on-screen objective to clear levels and achieve high scores.',
        rules: ['Tap or swipe to control gameplay.', 'Reach the target score to clear each stage.'],
        controls: 'Touch screen or use keyboard controls.',
        proTips: ['Practice regularly to master the mechanics.'],
      },
      achievements: [
        { id: 'default_play', title: 'First Game', desc: 'Play your first match', icon: '🎮', maxProgress: 1 },
      ],
      about: {
        version: '1.0.0',
        developer: 'TelePlay Game Studios',
        engine: 'Web Canvas Engine',
        features: ['Leaderboard integration', 'Offline progress tracking'],
      },
    }
  );
};
