import { ColorDefinition, ColorTapSprintLevel, ColorId } from './types';

export const COLOR_DEFINITIONS: Record<ColorId, ColorDefinition> = {
  BLUE: {
    id: 'BLUE',
    name: 'BLUE',
    bgHex: '#1D4ED8', // Rich vivid blue
    targetHex: '#2563EB',
    textOnCardHex: '#FFFFFF',
  },
  RED: {
    id: 'RED',
    name: 'RED',
    bgHex: '#DC2626', // Vibrant candy red
    targetHex: '#EF4444',
    textOnCardHex: '#FFFFFF',
  },
  GREEN: {
    id: 'GREEN',
    name: 'GREEN',
    bgHex: '#16A34A', // Saturated green
    targetHex: '#22C55E',
    textOnCardHex: '#FFFFFF',
  },
  LIME: {
    id: 'LIME',
    name: 'LIME',
    bgHex: '#84CC16', // High-energy lime
    targetHex: '#84CC16',
    textOnCardHex: '#FFFFFF',
  },
  YELLOW: {
    id: 'YELLOW',
    name: 'YELLOW',
    bgHex: '#EAB308', // Sweet lemon yellow
    targetHex: '#CA8A04',
    textOnCardHex: '#000000',
  },
  ORANGE: {
    id: 'ORANGE',
    name: 'ORANGE',
    bgHex: '#EA580C', // Bright tangerine orange
    targetHex: '#F97316',
    textOnCardHex: '#FFFFFF',
  },
  PURPLE: {
    id: 'PURPLE',
    name: 'PURPLE',
    bgHex: '#7E22CE', // Deep grape purple
    targetHex: '#9333EA',
    textOnCardHex: '#FFFFFF',
  },
  PINK: {
    id: 'PINK',
    name: 'PINK',
    bgHex: '#EC4899', // Berry pink
    targetHex: '#F43F5E',
    textOnCardHex: '#FFFFFF',
  },
  CYAN: {
    id: 'CYAN',
    name: 'CYAN',
    bgHex: '#06B6D4', // Tropical cyan
    targetHex: '#0891B2',
    textOnCardHex: '#FFFFFF',
  },
};

export const COLOR_TAP_SPRINT_LEVELS: ColorTapSprintLevel[] = [
  // Levels 1-5: Introductory Sprint
  {
    levelNumber: 1,
    name: 'Sweet Starter',
    targetCorrectTaps: 15,
    initialTimeSeconds: 36,
    timeBonusSeconds: 1.5,
    timePenaltySeconds: 3.5,
    cardCount: 4,
    useStroopDecoy: false,
    colorPool: ['BLUE', 'RED', 'GREEN', 'YELLOW', 'ORANGE'],
  },
  {
    levelNumber: 2,
    name: 'Sugar Rush',
    targetCorrectTaps: 18,
    initialTimeSeconds: 36,
    timeBonusSeconds: 1.4,
    timePenaltySeconds: 3.5,
    cardCount: 4,
    useStroopDecoy: false,
    colorPool: ['BLUE', 'GREEN', 'PURPLE', 'ORANGE', 'YELLOW'],
  },
  {
    levelNumber: 3,
    name: 'Candy Twist',
    targetCorrectTaps: 20,
    initialTimeSeconds: 35,
    timeBonusSeconds: 1.4,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'ORANGE', 'CYAN', 'LIME', 'PURPLE'],
  },
  {
    levelNumber: 4,
    name: 'Jelly Dash',
    targetCorrectTaps: 22,
    initialTimeSeconds: 35,
    timeBonusSeconds: 1.3,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['YELLOW', 'LIME', 'PINK', 'RED', 'CYAN', 'BLUE'],
  },
  {
    levelNumber: 5,
    name: 'Berry Burst',
    targetCorrectTaps: 24,
    initialTimeSeconds: 35,
    timeBonusSeconds: 1.3,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['PURPLE', 'PINK', 'RED', 'BLUE', 'GREEN', 'ORANGE'],
  },

  // Levels 6-10: Rapid Sprint
  {
    levelNumber: 6,
    name: 'Citrus Spark',
    targetCorrectTaps: 25,
    initialTimeSeconds: 34,
    timeBonusSeconds: 1.3,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['LIME', 'GREEN', 'YELLOW', 'ORANGE', 'CYAN', 'RED'],
  },
  {
    levelNumber: 7,
    name: 'Caramel Cruise',
    targetCorrectTaps: 26,
    initialTimeSeconds: 34,
    timeBonusSeconds: 1.3,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'PURPLE', 'YELLOW', 'PINK', 'GREEN', 'ORANGE'],
  },
  {
    levelNumber: 8,
    name: 'Frosting Flash',
    targetCorrectTaps: 27,
    initialTimeSeconds: 34,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['CYAN', 'BLUE', 'LIME', 'PURPLE', 'PINK', 'YELLOW'],
  },
  {
    levelNumber: 9,
    name: 'Taffy Turbo',
    targetCorrectTaps: 28,
    initialTimeSeconds: 33,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['RED', 'PINK', 'ORANGE', 'YELLOW', 'LIME', 'GREEN'],
  },
  {
    levelNumber: 10,
    name: 'Lollipop Lane',
    targetCorrectTaps: 30,
    initialTimeSeconds: 33,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'CYAN', 'PURPLE', 'PINK', 'RED', 'LIME', 'YELLOW'],
  },

  // Levels 11-15: Stroop Reflex Ramp
  {
    levelNumber: 11,
    name: 'Neon Swirl',
    targetCorrectTaps: 30,
    initialTimeSeconds: 33,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['CYAN', 'BLUE', 'LIME', 'GREEN', 'ORANGE', 'RED'],
  },
  {
    levelNumber: 12,
    name: 'Gummy Glaze',
    targetCorrectTaps: 31,
    initialTimeSeconds: 32,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.0,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['PURPLE', 'PINK', 'RED', 'YELLOW', 'LIME', 'CYAN'],
  },
  {
    levelNumber: 13,
    name: 'Sprinkle Sprint',
    targetCorrectTaps: 32,
    initialTimeSeconds: 32,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.2,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['ORANGE', 'YELLOW', 'RED', 'PINK', 'PURPLE', 'BLUE'],
  },
  {
    levelNumber: 14,
    name: 'Mint Mirage',
    targetCorrectTaps: 33,
    initialTimeSeconds: 32,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.2,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['GREEN', 'LIME', 'CYAN', 'BLUE', 'YELLOW', 'ORANGE'],
  },
  {
    levelNumber: 15,
    name: 'Bubblegum Blitz',
    targetCorrectTaps: 34,
    initialTimeSeconds: 32,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.2,
    cardCount: 6,
    useStroopDecoy: true,
    colorPool: ['PINK', 'PURPLE', 'RED', 'ORANGE', 'BLUE', 'CYAN', 'LIME'],
  },

  // Levels 16-20: 8-Card Grid Challenge
  {
    levelNumber: 16,
    name: 'Sundae Surge',
    targetCorrectTaps: 34,
    initialTimeSeconds: 32,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.2,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'CYAN', 'GREEN', 'LIME', 'RED', 'ORANGE', 'YELLOW', 'PURPLE'],
  },
  {
    levelNumber: 17,
    name: 'Marshmallow Matrix',
    targetCorrectTaps: 35,
    initialTimeSeconds: 31,
    timeBonusSeconds: 1.2,
    timePenaltySeconds: 4.2,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['PINK', 'PURPLE', 'RED', 'ORANGE', 'YELLOW', 'GREEN', 'CYAN', 'BLUE'],
  },
  {
    levelNumber: 18,
    name: 'Toffee Tempest',
    targetCorrectTaps: 35,
    initialTimeSeconds: 31,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.2,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['LIME', 'GREEN', 'CYAN', 'BLUE', 'PURPLE', 'PINK', 'ORANGE', 'RED'],
  },
  {
    levelNumber: 19,
    name: 'Sorbet Speed',
    targetCorrectTaps: 36,
    initialTimeSeconds: 31,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['YELLOW', 'ORANGE', 'RED', 'PINK', 'PURPLE', 'CYAN', 'BLUE', 'LIME'],
  },
  {
    levelNumber: 20,
    name: 'Cupcake Chaos',
    targetCorrectTaps: 36,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'CYAN', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'RED', 'PINK'],
  },

  // Levels 21-25: Deceptive Shades
  {
    levelNumber: 21,
    name: 'Cyan Blue Mirage',
    targetCorrectTaps: 37,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'CYAN', 'PURPLE', 'PINK', 'GREEN', 'LIME', 'YELLOW', 'ORANGE'],
  },
  {
    levelNumber: 22,
    name: 'Lime Green Labyrinth',
    targetCorrectTaps: 37,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['GREEN', 'LIME', 'YELLOW', 'ORANGE', 'RED', 'PINK', 'PURPLE', 'CYAN'],
  },
  {
    levelNumber: 23,
    name: 'Pink Purple Panic',
    targetCorrectTaps: 38,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['PINK', 'PURPLE', 'RED', 'BLUE', 'CYAN', 'LIME', 'GREEN', 'YELLOW'],
  },
  {
    levelNumber: 24,
    name: 'Amber Glow Rush',
    targetCorrectTaps: 38,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['ORANGE', 'YELLOW', 'RED', 'PINK', 'LIME', 'GREEN', 'CYAN', 'BLUE'],
  },
  {
    levelNumber: 25,
    name: 'Rainbow Frenzy',
    targetCorrectTaps: 38,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 8,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },

  // Levels 26-30: 9-Card Full Spectrum
  {
    levelNumber: 26,
    name: 'Spectrum 3x3',
    targetCorrectTaps: 39,
    initialTimeSeconds: 30,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 27,
    name: 'Sugar Spark Vortex',
    targetCorrectTaps: 39,
    initialTimeSeconds: 29,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 28,
    name: 'Neon Jelly Apex',
    targetCorrectTaps: 40,
    initialTimeSeconds: 29,
    timeBonusSeconds: 1.1,
    timePenaltySeconds: 4.5,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 29,
    name: 'Frosting Fury',
    targetCorrectTaps: 40,
    initialTimeSeconds: 29,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 4.8,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 30,
    name: 'Caramel Cascade',
    targetCorrectTaps: 40,
    initialTimeSeconds: 29,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 4.8,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },

  // Levels 31-35: Ultra-Reflex Tournament
  {
    levelNumber: 31,
    name: 'Pastel Overdrive',
    targetCorrectTaps: 41,
    initialTimeSeconds: 28,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 4.8,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 32,
    name: 'Candy Core Cyclone',
    targetCorrectTaps: 41,
    initialTimeSeconds: 28,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 4.8,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 33,
    name: 'Glaze Velocity',
    targetCorrectTaps: 42,
    initialTimeSeconds: 28,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 34,
    name: 'Gummy Gauntlet',
    targetCorrectTaps: 42,
    initialTimeSeconds: 28,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 35,
    name: 'Prismatic Blitz',
    targetCorrectTaps: 43,
    initialTimeSeconds: 28,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },

  // Levels 36-40: Grandmaster Apex Finals
  {
    levelNumber: 36,
    name: 'Stroop Master Mind',
    targetCorrectTaps: 43,
    initialTimeSeconds: 27,
    timeBonusSeconds: 1.0,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 37,
    name: 'Chromatic Overload',
    targetCorrectTaps: 44,
    initialTimeSeconds: 27,
    timeBonusSeconds: 0.9,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 38,
    name: 'Hyper-Sprint Inferno',
    targetCorrectTaps: 44,
    initialTimeSeconds: 27,
    timeBonusSeconds: 0.9,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 39,
    name: 'Penultimate Sugar Storm',
    targetCorrectTaps: 45,
    initialTimeSeconds: 26,
    timeBonusSeconds: 0.9,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
  {
    levelNumber: 40,
    name: 'Grandmaster Sprint Finale',
    targetCorrectTaps: 45,
    initialTimeSeconds: 26,
    timeBonusSeconds: 0.9,
    timePenaltySeconds: 5.0,
    cardCount: 9,
    useStroopDecoy: true,
    colorPool: ['BLUE', 'RED', 'GREEN', 'LIME', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'CYAN'],
  },
];

export function getColorTapSprintLevel(levelNum: number): ColorTapSprintLevel {
  const lvl = COLOR_TAP_SPRINT_LEVELS.find((l) => l.levelNumber === levelNum);
  return lvl || COLOR_TAP_SPRINT_LEVELS[0];
}
